-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 13:23:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Scientist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scientist` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_year` INT(4) NOT NULL,
  `death_year` INT(4) NULL,
  `birth_place` VARCHAR(100) NOT NULL,
  `field` VARCHAR(100) NULL,
  `alma_mater` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discovery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Discovery` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `year` YEAR NOT NULL,
  `place` VARCHAR(100) NOT NULL,
  `description` VARCHAR(9999) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discovery_has_Scientist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Discovery_has_Scientist` (
  `Discovery_id` INT NOT NULL,
  `Scientist_id` INT NOT NULL,
  PRIMARY KEY (`Discovery_id`, `Scientist_id`),
  INDEX `fk_Discovery_has_Scientist_Scientist1_idx` (`Scientist_id` ASC) VISIBLE,
  INDEX `fk_Discovery_has_Scientist_Discovery_idx` (`Discovery_id` ASC) VISIBLE,
  CONSTRAINT `fk_Discovery_has_Scientist_Discovery`
    FOREIGN KEY (`Discovery_id`)
    REFERENCES `mydb`.`Discovery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Discovery_has_Scientist_Scientist1`
    FOREIGN KEY (`Scientist_id`)
    REFERENCES `mydb`.`Scientist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
